band :
    type: rest
    resource: "TroobApiBundle:BandApi"
    name_prefix: api_
    
album :
    type: rest
    resource: "TroobApiBundle:AlbumApi"
    name_prefix: api_
    
music :
    type: rest
    resource: "TroobApiBundle:MusicApi"
    name_prefix: api_