band:
    path:     /band/
    defaults: { _controller: "TroobApiBundle:Band:index" }

band_show:
    path:     /band/{id}/show
    defaults: { _controller: "TroobApiBundle:Band:show" }

band_new:
    path:     /band/new
    defaults: { _controller: "TroobApiBundle:Band:new" }

band_create:
    path:     /band/create
    defaults: { _controller: "TroobApiBundle:Band:create" }
    requirements: { _method: post }

band_edit:
    path:     /band/{id}/edit
    defaults: { _controller: "TroobApiBundle:Band:edit" }

band_update:
    path:     /band/{id}/update
    defaults: { _controller: "TroobApiBundle:Band:update" }
    requirements: { _method: post|put }

band_delete:
    path:     /band/{id}/delete
    defaults: { _controller: "TroobApiBundle:Band:delete" }
    requirements: { _method: post|delete }
    
album:
    path:     /album/
    defaults: { _controller: "TroobApiBundle:Album:index" }

album_show:
    path:     /album/{id}/show
    defaults: { _controller: "TroobApiBundle:Album:show" }

album_new:
    path:     /album/new
    defaults: { _controller: "TroobApiBundle:Album:new" }

album_create:
    path:     /album/create
    defaults: { _controller: "TroobApiBundle:Album:create" }
    requirements: { _method: post }

album_edit:
    path:     /album/{id}/edit
    defaults: { _controller: "TroobApiBundle:Album:edit" }

album_update:
    path:     /album/{id}/update
    defaults: { _controller: "TroobApiBundle:Album:update" }
    requirements: { _method: post|put }

album_delete:
    path:     /album/{id}/delete
    defaults: { _controller: "TroobApiBundle:Album:delete" }
    requirements: { _method: post|delete }
    
music:
    path:     /music/
    defaults: { _controller: "TroobApiBundle:Music:index" }

music_show:
    path:     /music/{id}/show
    defaults: { _controller: "TroobApiBundle:Music:show" }

music_new:
    path:     /music/new
    defaults: { _controller: "TroobApiBundle:Music:new" }

music_create:
    path:     /music/create
    defaults: { _controller: "TroobApiBundle:Music:create" }
    requirements: { _method: post }

music_edit:
    path:     /music/{id}/edit
    defaults: { _controller: "TroobApiBundle:Music:edit" }

music_update:
    path:     /music/{id}/update
    defaults: { _controller: "TroobApiBundle:Music:update" }
    requirements: { _method: post|put }

music_delete:
    path:     /music/{id}/delete
    defaults: { _controller: "TroobApiBundle:Music:delete" }
    requirements: { _method: post|delete }