parameters:
#    troob_api.example.class: Troob\ApiBundle\Example

services:
#    troob_api.example:
#        class: %troob_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
