parameters:

services:
    app.cors_listener:
        class:      Troob\ApiBundle\Services\Cors
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }